# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receiver.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_1.setGeometry(QtCore.QRect(0, 0, 480, 360))
        self.widget_1.setObjectName("widget_1")
        self.exitButton = QtWidgets.QPushButton(self.widget_1)
        self.exitButton.setGeometry(QtCore.QRect(130, 260, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.exitButton.setFont(font)
        self.exitButton.setDefault(False)
        self.exitButton.setObjectName("exitButton")
        self.receiveButton = QtWidgets.QPushButton(self.widget_1)
        self.receiveButton.setGeometry(QtCore.QRect(130, 160, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.receiveButton.setFont(font)
        self.receiveButton.setDefault(False)
        self.receiveButton.setObjectName("receiveButton")
        self.receiveLabel = QtWidgets.QLabel(self.widget_1)
        self.receiveLabel.setGeometry(QtCore.QRect(60, 20, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.receiveLabel.setFont(font)
        self.receiveLabel.setText("")
        self.receiveLabel.setObjectName("receiveLabel")
        self.receiveButton.raise_()
        self.exitButton.raise_()
        self.receiveLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exitButton.setText(_translate("MainWindow", "退出程序"))
        self.receiveButton.setText(_translate("MainWindow", "接收数据"))
